graph TD;
    A[Request] --> B(Pre-requisites)
    B --> C{Expertise Required?}
    C -->|No| D(Mark for enablement) --> A
    C -->|Yes| F{Lead/Manager triage}
    F -->|High Difficulty| Q(Solution Lead)
    F -->|Medium Difficulty| M{CSE Specialist}
    M --> |Unresolved| Q
    Q --> |resolved| I
    I --> |inform| Y[Customer]
    M --> |Resolved| I(CSM)
    Q --> |Unresolved - break/fix| I(CSM)
    I --> |Escalate| T(Support/Product Engineering - break/fix)
    T --> |Resolved| I(CSM)
    B -->|Not Met| U(Request More Information)
    U --> B

